# Generated by Django 5.0 on 2023-12-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('movies', models.CharField(blank=True, max_length=200, null=True)),
                ('movies_id', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('categories', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('questions', models.CharField(blank=True, max_length=200, null=True)),
                ('questions_id', models.CharField(blank=True, max_length=200, null=True)),
                ('categories_id', models.CharField(blank=True, max_length=200, null=True)),
                ('creator', models.CharField(blank=True, max_length=200, null=True)),
                ('creator_id', models.CharField(blank=True, max_length=200, null=True)),
                ('users', models.CharField(blank=True, max_length=200, null=True)),
                ('users_id', models.CharField(blank=True, max_length=200, null=True)),
                ('winner', models.CharField(blank=True, max_length=200, null=True)),
                ('winner_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_started', models.BooleanField(default=False)),
                ('is_waiting', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False)),
                ('is_ready_to_start', models.BooleanField(default=False)),
                ('is_ready_to_finish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('rating', models.FloatField(default=0)),
                ('genre', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(default=0)),
                ('director', models.CharField(blank=True, max_length=200, null=True)),
                ('actors', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('won_categories', models.CharField(blank=True, max_length=200, null=True)),
                ('won_games_id', models.CharField(blank=True, max_length=200, null=True)),
                ('won_categories_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
