# Generated by Django 5.0 on 2023-12-26 19:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='players',
            new_name='participants',
        ),
        migrations.AddField(
            model_name='game',
            name='mode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='my_games',
            field=models.ManyToManyField(related_name='players', to='api.game'),
        ),
        migrations.AddField(
            model_name='submition',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='code',
            field=models.CharField(default=api.models.generate_code_for_game, max_length=6, unique=True),
        ),
    ]
