# Generated by Django 5.0 on 2024-01-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_players_game_participants_game_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='host',
            field=models.CharField(max_length=50),
        ),
    ]
