# Generated by Django 5.0 on 2024-01-04 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_game_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_place', models.IntegerField(default=0)),
                ('second_place', models.IntegerField(default=0)),
                ('third_place', models.IntegerField(default=0)),
                ('all_games', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.playerscore'),
        ),
    ]
