# Generated by Django 5.0 on 2024-01-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_playerscore_alter_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user_id',
            field=models.CharField(default='-1', max_length=50, unique=True),
        ),
    ]
