# Generated by Django 5.0 on 2024-01-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_player_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='user_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
