# Generated by Django 5.0 on 2024-01-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_player_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='my_games',
            field=models.ManyToManyField(default=set, related_name='players', to='api.game'),
        ),
    ]
