# Generated by Django 5.0 on 2024-01-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_player_my_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscore',
            name='created',
            field=models.IntegerField(default=0),
        ),
    ]
