# Generated by Django 5.0 on 2024-01-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_playerscore_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mode',
            field=models.IntegerField(default=0),
        ),
    ]
