# Generated by Django 5.0 on 2024-02-14 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_movie_year_category_game_id_movie_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submition',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
