# Generated by Django 5.0 on 2024-02-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_submition_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='voters',
            field=models.ManyToManyField(default=set, to='api.player'),
        ),
    ]
